### ISSUE TITLE
"now exiting Console" message in beamer presentation

### ISSUE THREAD

**Issue by trashyms** [gpoore/pythontex#100]
Hello.
I have on some of my beamer slides presentation this message 

    now exiting Console

after two empty lines.
Is there any way to avoid this behavior ?

Thanks.

**Comment by obtitus** [comment]
Can you provide a minimal example? I have been using pythontex in beamer for years and have never seen this.
-- 
Øystein Bjørndal

**Comment by gpoore** [comment]
Python 3.6 changed the behavior of the [`code` module](https://docs.python.org/3/library/code.html) so that this is now the default behavior. It looks like every use of `InteractiveConsole.interact()` will need to be replaced with `InteractiveConsole.interact(exitmsg='')`, but I haven't had a chance to test this yet.

**Comment by trashyms** [comment]
[![enter image description here][1]][1]

I do produce slides for my training presentation with Beamer.
To execute Python code and show result I use the `pythontex` package.

When I use `\pyconsole` environment, I always have this message after the result of the last `\pyconsole` command:

     now exiting Console ...

I have produced a minimal example of output below.

Is there any way to avoid this behavior?

filename: `pythontex_error.tex`

    \RequirePackage{currfile}
    \documentclass{beamer}

    \mode<presentation>{
    \usetheme{Boadilla}
    \usecolortheme {beaver}}
    \usepackage{pythontex}

    \begin{document}

    \begin{frame}
      \frametitle{ My error : reproductibility }
      \begin{block}{Proportion of couples (a,b) $ \in \left \{ a, ..,z,A,..Z \right \}$}
        \input{./pyconsole_code}
      \end{block}

      \begin{block}{Last pythontex pyconsole environment}
        \input{./pyconsole_last_code}
      \end{block}

      \begin{block}{Have been added on the last pyconsole  output }
        \pyv{  }\\
        \pyv{  }\\
        \pyv{now exiting Console...}
      \end{block}
    \end{frame}
    \end{document}


filename: `pyconsole_code.tex`


    \tiny
    \begin{pyconsole}
    a = [(x, y) for x in range(52) for y in range(52) ]
    b = [(x, y) for x in range(52) for y in range(52) if x != y]
    c = [(x, y) for x in range(52) for y in range(52) if x<y]
    \end{pyconsole}

    \footnotesize
    \begin{pyconsole}
    len(b)/len(a)*100, len(c)/len(a)*100
    \end{pyconsole}


filename: `pyconsole_last_code.tex`

    \begin{pyconsole}
    print("This is the last pyconsole environment")
    \end{pyconsole}


  [1]: https://i.stack.imgur.com/Py28U.jpg

**Comment by gpoore** [comment]
This should be fixed by the last commit. You can replace your current `pythontex3.py` with the new one.

**Comment by trashyms** [comment]
Hello.
Thanks for your answer.

I tried to do so..
But it seems that I have more file to modify:
  /usr/local/texlive/2015/texmf-dist/scripts/pythontex/pythontex3.py
  /usr/local/texlive/2015/texmf-dist/scripts/pythontex/pythontex2.py
  /usr/local/texlive/2015/texmf-dist/scripts/pythontex/depythontex3.py
  /usr/local/texlive/2015/texmf-dist/scripts/pythontex/depythontex2.py
  /usr/local/texlive/2015/texmf-dist/source/latex/pythontex/pythontex.dtx

So I did, but after that, some of my beamer presentation do not compile.
I am still searching for a solution.

I will give you more information after I have investigate more.

Best regards.

**Comment by gpoore** [comment]
@trashyms I was forgetting about the version check, so you are correct, several files will need to be replaced. There is also `pythontex.sty`, which isn't in your list. There is a [Python installation script](https://github.com/gpoore/pythontex/blob/master/pythontex/pythontex_install.py) that might help you do some of this automatically.

**Comment by trashyms** [comment]
Hello!
I made these modifications but one some of my presentation I have this error.

```
trashyms:slides - python$ pythontex 02_interpreters_and_types
This is PythonTeX 0.16dev
Traceback (most recent call last):
  File "/Library/TeX/texbin/pythontex", line 62, in <module>
    pythontex.main()
  File "/usr/local/texlive/2015/texmf-dist/scripts/pythontex/pythontex3.py", line 2679, in main
    do_multiprocessing(data, temp_data, old_data, engine_dict)
  File "/usr/local/texlive/2015/texmf-dist/scripts/pythontex/pythontex3.py", line 1293, in do_multiprocessing
    engine_dict[family].commands,
AttributeError: 'SubCodeEngine' object has no attribute 'commands'
```

I don't have any clue about how to overcome with this problem.

Do you have any suggestion ?

Best regards.

**Comment by gpoore** [comment]
@trashyms My guess would be that there is still an old copy of `pythontex_engines.py` that needs to be replaced with a new version, or possibly another file. Your sample document is compiling fine for me, with the latest versions of all code.

**Comment by trashyms** [comment]
@gpoore I will check that. Thanks.
