### ISSUE TITLE
Not able to run pythontex !!

### ISSUE THREAD

**Issue by sumandoc** [gpoore/pythontex#102]
`\documentclass{article}
\usepackage{pythontex}
\begin{document}
Here is value of 2 raised to power 3 = \py{2**3}.	
\begin{pyconsole}
	var = 1 + 1
	var
\end{pyconsole}		
\end{document}`

This is the LaTeX code that I am trying to run in TexStudio with TexLive 2017.
I am on Windows 10 64 bit with Anaconda Python v3.6.1 installed and its in path.

However I am getting this output.
>Here is value of 2 raised to power 3 = ??.
>?? PythonTeX ??

Any help?

**Comment by gpoore** [comment]
Are you running LaTeX, then `pythontex.exe`, and then LaTeX? That looks like what happens if things aren't compiled completely.

**Comment by sumandoc** [comment]
How to do that? Any reference to video tutorial. 

Went through the docs at https://tug.org/tug2013/slides/Mertz-A_Gentle_Introduction_to_PythonTeX.pdf. 

But unable to figure out.

M still roaming. 

Eagerly waiting for the help!!

**Comment by obtitus** [comment]
How are you currently compiling the latex document? Are you using TeXstudio or similar?

In a unix based system I would run the following 3 commands (if the latex file is ‘foo.tex’)
pdflatex foo.tex
pythontex foo.tex
pdflatex foo.tex

-- 
Øystein Bjørndal

**Comment by sumandoc** [comment]
Yeah I am using TexStudio. 

With those three commands from terminal(command prompt in my Windows), yeah it works. Thanks.

**Comment by fazalhaq666** [comment]
> `\documentclass{article} \usepackage{pythontex} \begin{document} Here is value of 2 raised to power 3 = \py{2**3}. \begin{pyconsole} var = 1 + 1 var \end{pyconsole} \end{document}`
> 
> This is the LaTeX code that I am trying to run in TexStudio with TexLive 2017.
> I am on Windows 10 64 bit with Anaconda Python v3.6.1 installed and its in path.
> 
> However I am getting this output.
> 
> > Here is value of 2 raised to power 3 = ??.
> > ?? PythonTeX ??
> 
> Any help?

> I have the same problem, but I use TexMaker. How can I solve this problem?

**Comment by gpoore** [comment]
@fazalhaq666 You can run compile commands in the terminal, using commands similar to those given above. Or you can consult the documentation for TexMaker to figure out how to get it to do this for you. Something like this might also be useful: https://tex.stackexchange.com/questions/431523/texmaker-miktex-using-pythontex.
