### ISSUE TITLE
About Perl 6 support 

### ISSUE THREAD

**Issue by sumandoc** [gpoore/pythontex#104]
Hi there,

My experience with pythontex  has been smooth and it has made life lot better.

I would love to see Perl 6(https://perl6.org/) support in pythontex soon.

Best regards,
sumandoc

**Comment by gpoore** [comment]
I'm currently rewriting the code execution core of PythonTeX. Once that is done, I'll look into adding Perl 5 and 6. If you need Perl 6 sooner than that, you could also look at `pythontex_engines.py` and probably get a basic version working relatively easily by using Python and Ruby as a guide.

**Comment by gpoore** [comment]
I've added basic Perl 6 support. Currently, there is no utilities class or equivalent (nothing equivalent to `pytex` in Python). I will look into adding more advanced features like that later.
