### ISSUE TITLE
How to convert \py to number

### ISSUE THREAD

**Issue by kzhk75** [gpoore/pythontex#108]
Hi,

I want to use PythonTex in [siunitx.sty](https://www.ctan.org/pkg/siunitx?lang=en).

Here is my simple code:
```TeX
\documentclass{article}
\usepackage{amsmath,amsfonts}
\usepackage{pythontex}
\usepackage{siunitx}
\begin{document}
\begin{pycode}
(m, a ) = (5, 2)
F = m*a
\end{pycode}
\begin{align*}
  ma =& F&\\
  a =& \dfrac{F}{a}
       =  \dfrac{\py{F}}{\py{a}}
       = \py{a}
       = {\py{a}} \ \si{m/s^2}
%error%     = \SI{\py{a}}{m/s^2}  
\end{align*}
\end{document}
```
It works _without_ the %error% line above.

**With** the %error% line, siunitx error says after compiling with AUCTeX:
> ERROR: siunitx error: "invalid-token-in-number"
> 
> --- TeX said ---
> ! 
> ! Invalid token '\py ' in numerical input.
> ! 
> ! See the siunitx documentation for further information.
> ! 
> ! For immediate help type H <return>.
> !...............................................  
>                                                   
> l.22 \end{align*}
>                  
> --- HELP ---
> From the .log file...
> 
> |'''''''''''''''''''''''''''''''''''''''''''''''
> | Numbers can only contain tokens defined using the 'input-...' options:
> | the token '\py ' is not set up as a valid part of a number.
> |...............................................

As far as I read [siunitx.pdf](http://mirrors.ctan.org/macros/latex/contrib/siunitx/siunitx.pdf), \<*number*\> should NOT be variable in \SI[⟨options⟩]{⟨*number*⟩}[⟨pre-unit⟩]{⟨unit⟩}.

How can I comvert \py{a} to "number" in siunitx?

**Comment by obtitus** [comment]
I would recommend creating the string on the python side, @gpoore can give more details (and workarounds?). You basically only need `r'\SI{%s}{%s}' % (num, unit)` on the python side; but I just uploaded the code that I use for this exact same purpose:
https://github.com/obtitus/pysiprefix
It has a few more bells and whistles, such as support for complex numbers and si-prefix scaling (kilo, mega, ...).

**Comment by gpoore** [comment]
The most general solution is to do something like https://tex.stackexchange.com/a/122004/10742, combined with some more advanced number and unit formatting code like that given by @obtitus as necessary. I suppose it might be possible theoretically to rewrite the `siunitx` number parsing code to work with `\py`, but I've never tried...it would give essentially the same result as the `\pySI` approach at the cost of a lot of low-level TeX programming.

Another option is `\SI[parse-numbers=false]{\py{a}}{m/s^2}`, but this will only really do what you want when `str(a)` formats the number exactly the way you want.

**Comment by kzhk75** [comment]
Thanks for your comment.
I find another way to do this with pysub: https://tex.stackexchange.com/a/65294/42259
I made a simple example below. r'\SI{%s}{%s}' % (num, unit) works in pycode, but not in \py.
When I use pysub, I find that some commas can not appear in tikz. I should try to follow links from @gpoore and @obtitus .

```TeX
\begin{pycode}
(m, a ) = (5, 2)
F = m*a
\end{pycode}
%
\begin{pysub}
  % https://tex.stackexchange.com/a/65294/42259 
  \begin{align*}
    ma =& F&\\
    a =& \dfrac{F}{a} =  \dfrac{\py{F}}{\py{a}}
         = {\py{a}} \ \si{m/s^2} = \SI{!{a}}{m/s^2} &
  \end{align*}
  The accelaration is \SI{!{a}}{m/s^2}.\\
\end{pysub}
% with the comments
\begin{pycode}
(M, v0, v1) = (10, 5, 10)
I = M*(v1-v0)
IwUnt=r'\SI{%s}{%s}' % (I, "kg.m/s")
print(IwUnt)
\end{pycode}
\begin{align*}
  I &= M\cdot v_1 - m\cdot v_0
    =\SI[parse-numbers=false]{\py{I}}{kg.m/s}
    =\py{print(IwUnt)}&
\end{align*}
```

**Comment by gpoore** [comment]
@kzhk75 `pysub` and the corresponding `\pys` command are also a good approach. In your example, you could replace `\dfrac{\py{F}}{\py{a}}` with `\dfrac{!{F}}{!{a}}` if you wanted to make things a little more compact.

`\py{r'\SI{%s}{%s}' % (num, unit)}` works normally, but I discovered that if it (or just `\py` in general) is immediately after `align*`, then `align*` interferes with it (bug report in #109).

`pysub` should not affect commas. If you want to post an example, I can take a look.

**Comment by kzhk75** [comment]
Another example in a mathematical expression:
```TeX
\[
  I = \py{print(IwUnt)}
\]
```
It shows:
> *I*= 50 kg m/s*None*
. Is it also related to bug report in #109?

**Comment by gpoore** [comment]
@kzhk75 In that case, you want `\py{IwUnt}`. There's no need to print, because `\py` automatically inserts a string version of whatever variable it is given. Basically, `\py{IwUnt}` is essentially equivalent to `\pyc{print(IwUnt)}` (note the `\pyc`, not `\py`).

I've done a little more work on #109. It appears that there are only problems when `align*` contains an `\SI` with a `\py` inside it. If you replace `\SI[parse-numbers=false]{\py{I}}{kg.m/s}` with something like `\pys{\SI{!{I}}{kg.m/s}}` it seems to work fine. Since #109 is looking more like a triple package clash, I would recommend avoiding the `\py` inside `\SI` altogether.

**Comment by kzhk75** [comment]
I made two simple examples of tikz with/without pythontex.

The first one without \py works well:
```Tex
\usepackage{pythontex}
\usepackage{tikz}
\usetikzlibrary{datavisualization}  
\begin{document}
\begin{tikzpicture}
  \datavisualization [school book axes,
  visualize as smooth line]
  data {
    x, y
    -1.5, 2.25 
    -1, 1
    -.5, .25
    0, 0
    .5, .25
    1, 1
    1.5, 2.25
  };                               
\end{tikzpicture}
```

The second one with \py has an error:
```Tex
\begin{tikzpicture}
  \datavisualization [school book axes,
  visualize as smooth line]
  data {
    x, y
    -1.5, \py{(-1.5)**2}
    -1, 1
    -.5, .25
    0, 0
    .5, .25
    1, 1
    1.5, 2.25
  };                               
\end{tikzpicture}
```

> ERROR: Missing \endcsname inserted.
> 
> --- TeX said ---
> <to be read again> 
>                    \xdef 
> l.35   };
>          
> --- HELP ---
> From the .log file...
> 
> The control sequence marked <to be read again> should
> not appear between \csname and \endcsname.

In this error, I guess the end/return of \py loses '\n' . Is the error also connected to #109?

**Comment by gpoore** [comment]
@kzhk75 This isn't connected to #109. With tikz, you can't use `\py` inside of a line of commands/statement, due to how tikz operates. You can usually use `\py` to supply an entire line/statement of tikz code (start of line through semicolon at end), though. The `pysub` environment was largely created to work around these sorts of limitations.

**Comment by kzhk75** [comment]
Thanks for your advice, @gpoore .
```TeX
\pyc{a=(-1.5)**2}
\begin{pysub}
  \begin{tikzpicture}
    \datavisualization [school book axes,
    visualize as smooth line]
    data {
      x, y
      -1.5, !{a}
      -1, 1
      -.5, .25
      0, 0
      .5, .25
      1, 1
      1.5, 2.25
    };                               
  \end{tikzpicture}
\end{pysub}
```
