### ISSUE TITLE
Vim syntax highlight setup

### ISSUE THREAD

**Issue by konstunn** [gpoore/pythontex#110]
Could you please advise a plugin or a manual way how to set vim highlighting both TeX and Python code as well in a single file?

**Comment by gpoore** [comment]
I can see how that would be very useful. Unfortunately, I don't have enough experience customizing vim to be able to suggest anything. If you do find a solution, let me know and I can try to include some information in the documentation.

**Comment by ilynxphysicist** [comment]
You can do it manually. Look at wiki [Syntax Highlighting](http://vim.wikia.com/wiki/Syntax_highlighting). There is also a plugin for it, see at [SyntaxRange](https://vim.sourceforge.io/scripts/script.php?script_id=4168).

Or you may try to use "Markdown fenced languages" feature. You can read more about at [Vim-Markdown](https://github.com/tpope/vim-markdown). In this article you see how it works [Highlight #markdown fenced code syntax in #Vim](https://til.hashrocket.com/posts/e8915e62c0-highlight-markdown-fenced-code-syntax-in-vim). 

**---**
I'm using _NeoVim_ (_with VimTeX_) and it may works differently for _Vim_ (probably works as well, I tried just once and worked fine). You way try follows my steps:

- (Maybe you need install Tim Pope's Markdown plugin before; I didn't need.)
- Added to my config file:
`let g:markdown_fenced_languages = ['python', 'tex']`
- After open a .tex file I set the filetype as markdown, that is
 `set ft=markdown`. One can use autocmd adding to .vimrc:
`autocmd BufNewFile,BufReadPost *.tex set filetype=markdown`
- Optional (_recommended for long documents_):
`let g:markdown_minlines = 2000`

Example:

     1    | \iffalse                    % start commenting "```tex"
     2    | ```tex \fi                  % start TeX syntax highlighting (HL) / end comment
     ?    | TEX CODE   
     ?    | \iffalse                    % start commenting "```"
     ?    | ```                         % stop TeX syntax HL
     ?    | \fi                         % end comment
     ?    |\iffalse
     ?    |```python                    % start Python syntax HL
     ?    | SOME PYTHON CODE BLOCK
     ?    |\iffalse
     ?    |```                          % end Python syntax HL
     ?    |\iffalse
     ?    |\iffalse
     ?    |```tex \fi
     ?    | TEX CODE
     ?    | END DOCUMENT
 
We started with TeX syntax HL (for LaTeX code: preamble, etc..). **Then used \iffalse \fi to comment out "\`\`\`[tex/python]" and "\`\`\`" so that LaTeX don't complain about it and do not compile as well.** In some part of the code we wrote some Python code block; we wrapped it accordingly. Thus Vim recognize it as Python and HL it appropriately. We go 
back to LaTeX syntax HL till the end of the document. Since it was the last fenced code block we did not need to close it.
 
To do it faster you can use abbreviations or snippets.  For example, possibly useful abbreviations:
```
iab texHL \iffalse <CR>```tex \fi<CR>                            " start TeX HL
iab pyHL   \iffalse <CR>```python \fi<CR>                        " start Python Hl
iab sHL \iffalse<CR>```<CR>\fi<CR>                               " stop HL
```
Or use instead snippets (UltiSnips) like

      snippet HL "HL_code"
           \iffalse
           ```${2:python, tex} \fi
           ${1:code block}
           \iffalse
           ```
           \fi
           ${0}
      endsnippet

**----**

Well, it was kinda messy. Nevertheless, I hope this will help someone.
