### ISSUE TITLE
Speed up importing modules

### ISSUE THREAD

**Issue by konstunn** [gpoore/pythontex#112]
Is there a way to speed up (cache) imported modules so that I could not to reimport these on chunk rerun? Or maybe saving or restoring the interactive session (like in IPython) or so? This question is a little bit general, but however addresses the problem with the use of PythonTex.

**Comment by gpoore** [comment]
There isn't a way to do this currently. At the moment, the best way to deal with slow chunks is probably to split them up into separate independent sessions and save intermediate results using pickle, etc.

I've thought about this a little in the past. I suppose there might be a way to pickle everything at the end of each chunk, and on rerun load the pickled data from the last unchanged chunk. But that would add significant overhead and additional complexity.
