### ISSUE TITLE
Is there a way to have pythontex create a .tex file that can be imported like pyconsole

### ISSUE THREAD

**Issue by joelmiller** [gpoore/pythontex#118]
As a simple example, I'm using

\begin{pyconsole}
import numpy
x = numpy.array([0,1])
x*x
\end{pyconsole}

But if I send this to a publisher, they won't be happy to let my tex file run some python scripts (and more specifically I can't get the import to work on overleaf).  So I'd like to see if there's a way to generate a .tex file that is correctly formatted so that importing that .tex file produces the same result as the commands above.

**Comment by gpoore** [comment]
Take a look at the `depythontex` examples in the documentation. At least for simple cases, it can convert a tex file that uses `pythontex` into one that doesn't.
