### ISSUE TITLE
Relative path suport

### ISSUE THREAD

**Issue by pepramon** [gpoore/pythontex#119]
Hi all,

I would like to propose an enhancement that I think could be useful for a lot of people. I'm working with import package to maintain all my documents organizes and to be able to reuse in other documents.

¿I'ts possible to pythontex do a chdir when detect de subimport command?

Thanks for your time.

**Comment by gpoore** [comment]
You can probably do what you want by creating a new command, maybe something like this (untested):

```latex
\newcommand{\subimportwithchdir}[2]{%
  \pyc{os.chdir("#1")}%
  \subimport{#1}{#2}}
```
