### ISSUE TITLE
No file pythontex-files-gnuplottex/gnuplottex.pytxmcr.

### ISSUE THREAD

**Issue by arick-001** [gpoore/pythontex#120]
Hi,
When I use your package and follow your advice to compile the document,some thing wrong appear,like this warning:1.Non-existent printed content
                    2.No file pythontex-files-gnuplottex/gnuplottex.pytxmcr.
                    3.A "listing" environment already exists (PythonTeX) PythonTeX will not create one (PythonTeX) Use \setpythontexlistingenv to create a custom listing environment.
I check the pythontex-files-gnuplottex folder,ther is nothing in the folder,shows "Foloder is Empty",what's problem there lies.
My configuration:WIN7 SP1 ,texlive2016,python3.6.
Thanks for giving me some advice,the probelm puzzle me a several days.

**Comment by gpoore** [comment]
Did you get this resolved? I unfortunately missed this when you submitted it due to timing relative to work and holidays.
