### ISSUE TITLE
add R language support

### ISSUE THREAD

**Issue by dmpe** [gpoore/pythontex#121]
Join me in :+1: this issue

**Comment by gpoore** [comment]
Can you provide a little detail about why you're interested in R support, in spite of what already exists in Sweave and knitr? What do you see R support providing that hasn't already been done better elsewhere?

**Comment by EmmanuelCharpentier** [comment]
I'm looking around to find complements/alternatives to SageTeX. PythonTeX seems interesting, but I have not (yet) experiment it.

My interest has ben aroused by this issue. I happen to be an (applied) statistician), whho has to use `R` (intensely) and Sage (sometimes). In my current setup, compiling a docume,nt involves : 
```
emacs foo.Rnw --> knitr --> LaTeX --> (LaTeX -->) --> Sage --> LaTeX (--> LaTeX)
```

Emacs' `AUCTeX`, `Rnw-mode` and `sage_shell_mode` are of great help, but a more streamlined workflow would be welcome.
* Support for R in PythonTeX would probably allow that.
* An alternative might be  (persistent) `Sage` and `python` engines in `knitr`.
* Bonus : SageTeX's `makestatic` is currently broken, and not easily fixed. `depythontex` might come in handy...
* Potential drawback : `knitr`'s `cache` and `depends` features are _extremely_ handy, and really useful when working with modern techniques using resampling and/or MCMC, which may be unreasonably chronophage... I do not know yet how well PyhonTeX will behave in that aspect.

HTH,

**Comment by dmpe** [comment]
@gpoore sorry for replying very late. The problem I have faced was that my primary document was in latex (not in Rnw/knitr/whatever else - just pure latex) and I needed ability to insert R code without going into Rnw/knitr route. 
Not a problem anymore though but still nice to have feature

**Comment by gpoore** [comment]
I've added basic support for R. It is enabled via `\usepackage[usefamily=R]{pythontex}`. This provides `\R`, `\Rc` and `Rcode`, `\Rb` and `Rblock`, and `\Rv` and `Rverbatim`. 

There isn't an `Rconsole` yet. I'm thinking that a good first approximation might be to put commands in a file `commands.R` with `options(echo=TRUE)`, and process that with `Rscript`. I'd be open to any suggestions on processing commands to get results equivalent to an interactive session.

**Comment by dmpe** [comment]
hi, thank you ver much.
your idea sounds good - go ahead with that from myside

**Comment by EmmanuelCharpentier** [comment]
I didn't see the comment about the Oct 23, 2018.

If I understand correctly, that means that `Pythontex`'s support for `R` is essentially complete. Great !

Thank you a lot for this work. This alernative to `knitr` comes very handy when using a mixed-bag of languages (I tend to use `Sagemath` more and more...).
