### ISSUE TITLE
Update pythontex on Ubuntu 16.04.1 without using package manager?

### ISSUE THREAD

**Issue by reckoner** [gpoore/pythontex#122]
Hi,
The ``tlmgr`` package manager does not work on my distribution for some reason. I *do* have root access, however. Is it possible to update from version 14 to the latest version without using the TeX package manager? If so, how?

Thanks for all your great work.

**Comment by gpoore** [comment]
You can download the latest version from GitHub and use the included Python installation script. Depending on how old your TeX installation is, you might also need to manually update a few of your other packages. But in most cases that would probably be as simple as downloading the latest .sty file from CTAN and then replacing the old version.

You could also just try to install the latest TeX Live manually.
