### ISSUE TITLE
Julia 0.7 Support

### ISSUE THREAD

**Issue by tawheeler** [gpoore/pythontex#126]
The alpha version of [Julia 0.7 is ready for download](https://julialang.org/downloads/). Julia 1.0 is going to be Julia 0.7 with the deprecations removed. Would love to see support for this in pythontex.

Need to change pythontex_engines.py:

- Line 953 to: `mutable struct JuliaTeXUtils`
- Line 986  and 987 to use: `= AbstractString[]`
- Line 1098 to: `write(stderr, "{stderrdelim}\\n")`

**Comment by nathancarter** [comment]
This was really helpful to be able to temporarily patch my own `pythontex_engines.py` to work with Julia 0.7.  Thanks, @tawheeler.

For others who want this feature now, the file in question is at `/usr/local/texlive/2018/texmf-dist/scripts/pythontex/pythontex_engines.py` (at least for me).

**Comment by gpoore** [comment]
@tawheeler Thanks for this! Sorry for the delay. The new version will go on CTAN in the next couple of days.
