### ISSUE TITLE
PythonTex Logo Recovery

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#128]
Hi @gpoore , do you by any chance still have the logo I put together [a while ago](https://github.com/gpoore/pythontex/issues/34#issuecomment-34561383) for PythonTex? I seem to have misplaced it.

I'm at EuroSciPy and giving [a short demo on RepSeP](https://www.euroscipy.org/2018/descriptions/RepSeP%20-%20Reproducible%20Self-Publishing%20for%20Python-Based%20Research..html) and I'd like to better highlight PythonTeX. I think adding a logo would make it more memorable.

**Comment by gpoore** [comment]
Unfortunately, I don't have it. I remember looking at it, but didn't save anything locally.

**Comment by TheChymera** [comment]
Ok, I managed to recover the logo, but sadly not in time for the presentation.

Hopefully it will be more permanently available [here](http://chymera.eu/img/logos/pythontex.png), and [here](http://chymera.eu/img/logos/pythontex.svg). Additionally, it is [tracked](https://github.com/TheChymera/RepSeP/blob/master/img/pythontex.pdf) for newer versions of the reference RepSeP slides.
