### ISSUE TITLE
Improve latexmk compilation on first run (no manual invocation of pythontex)

### ISSUE THREAD

**Issue by kiryph** [gpoore/pythontex#132]
The documentation of *pythontex* (v0.16) explicitly describes how to compile a document using pythontex with `latexmk` (section 4.6.1). Therefore, I would assume this is a/the recommended way to do this.

However, there is a current limitation that on the first build `latexmk` does not detect that an invocation of `pythontex` is necessary despite that the log output explicitly says this:

```
❯ cat latexmkrc
push @generated_exts, "pytxcode";
add_cus_dep('pytxcode', 'tex', 0, 'pythontex');
sub pythontex { return system("pythontex \"$_[0]\""); }

❯ latexmk -pdf demo-pythontex-networkx.tex
Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "demo-pythontex-networkx.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./demo-pythontex-networkx.tex
LaTeX2e <2018-04-01> patch level 5
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2018/texmf-dist/tex/latex/pythontex/pythontex.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/fvextra/fvextra.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2018/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2018/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
<2008/02/07> (tvz)
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics/keyval.sty))
(/usr/local/texlive/2018/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2018/texmf-dist/tex/latex/lineno/lineno.sty))
(/usr/local/texlive/2018/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/local/texlive/2018/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/local/texlive/2018/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/local/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/local/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.c
ode.tex)))) (/usr/local/texlive/2018/texmf-dist/tex/latex/caption/newfloat.sty)
 (/usr/local/texlive/2018/texmf-dist/tex/latex/currfile/currfile.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2018/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2018/texmf-dist/tex/latex/filehook/filehook.sty)))
(/usr/local/texlive/2018/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-def/pdftex.def))
(./demo-pythontex-networkx.aux)
No file pythontex-files-demo-pythontex-networkx/demo-pythontex-networkx.pytxmcr
.
Run PythonTeX to create it.
(/usr/local/texlive/2018/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (./demo-pythontex-networkx.aux) )
No pages of output.
Transcript written on demo-pythontex-networkx.log.
=== TeX engine is 'pdfTeX'
Latexmk: Missing input file: 'pythontex-files-demo-pythontex-networkx/demo-pythontex-networkx.pytxmcr' from line
  'No file pythontex-files-demo-pythontex-networkx/demo-pythontex-networkx.pytxmcr.'
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Failure to make 'demo-pythontex-networkx.pdf'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: failed to create output file
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
```

The above log contains the lines:
```
No file pythontex-files-demo-pythontex-networkx/demo-pythontex-networkx.pytxmcr
.
Run PythonTeX to create it.
```

I consider this unsatisfying.

The author of latexmk provides a slightly more advanced configuration than the one given in the documentation of pythontex 0.16 on ctan:

http://ftp.math.purdue.edu/mirrors/ctan.org/support/latexmk/example_rcfiles/pythontex-latexmkrc

However, the description in the file states the same limitation.

Interestingly, the author mentions that he has the intention to improve this:

> This version also has a restriction that on initial runs pythontex
>  is not invoked.  Later runs after a modification of the source
>  file in the invoked python code do trigger the invocation of
>  pythontex. The planned future enhancements of latexmk should
>   remedy this.

However, in the last three releases after addition of the example rcfile v4.57, 4.59, 4.60a the situation has not changed. (from http://personal.psu.edu/jcc8/software/latexmk/versions.html)

I am not sure how this could be improved. Other tools such as asymptote, glossary work just fine. My current thoughts are

- add option to latexmk: `post_first_run_cmd`
- add option to latexmk to add manually files to the list of INPUT files taken from the `-recorder` option
- improve pythontex to make `latex -recorder` record files such as `pytxmcr` are required (as well as `pytex.add_dependencies(⟨dependencies⟩)`)

Does anyone know how this could/should (in the most sensible way) be resolved?

I personally consider latexmk one of the best build tools for latex projects. Other popular seem to be rubber and arara. But a quick google search for pythontex plus rubber/arara did not give any promising results.

**Comment by fmitha** [comment]
I just ran into this myself. So it's really still the case that `pythontex` needs to be run manually for the build to work? That does not seem very automatic. The 4.61 documentation has a section on `pythontex`, and suggests adding the following to `.latexmkrc`, though I have no clear idea what that configuration does. I added those lines.

add_cus_dep(’pytxcode’, ’tex’, 0, ’pythontex’);
sub pythontex { return system("pythontex \"$_[0]\""); }

**Comment by fmitha** [comment]
On further testing, those lines seem to work after all, which is confusing. But it would be nice if worked without having to add configuration. Here's what the relevant `latexmk` output looks like:

```
Latexmk: Missing input file: 'pythontex-files-smyt55/smyt55.pytxmcr' from line
  'No file pythontex-files-smyt55/smyt55.pytxmcr.'
Latexmk: References changed.
Latexmk: Log file says output to 'smyt55.pdf'
Latexmk: List of undefined refs and citations:
  Reference `2017.12.22' on page 1 undefined on input line 310
Rule 'cusdep pytxcode tex smyt55': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'smyt55.pytxcode'
------------
Run number 1 of rule 'cusdep pytxcode tex smyt55'
------------
=== TeX engine is 'pdfTeX'
Latexmk: applying rule 'cusdep pytxcode tex smyt55'...
For rule 'cusdep pytxcode tex smyt55', running '&do_cusdep( pythontex )' ...
This is PythonTeX 0.16

--------------------------------------------------
PythonTeX:  smyt55 - 0 error(s), 0 warning(s)

Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'pythontex-files-smyt55/smyt55.pytxmcr'
      'smyt55.aux'
```

**Comment by fmitha** [comment]
I think I misunderstood the topic of this issue. Which is that `pythontex` is not invoked on the *first* run. But is invoked on following runs. Which seems fine to me, though I suppose opinions differ.

 Anyway, sorry for the noise.

**Comment by kiryph** [comment]
Hi fmitha,

since I raised this issue on 22.10.2018, the author of latexmk has improved the support for pythontex in version 4.61 (25.10.2018)in particular by providing a new latexmkrc file when using pythontex

http://mirrors.ctan.org/support/latexmk/example_rcfiles/pythontex-latexmkrc

So my original problem is outdated. Therefore, I close this issue.

**Comment by fmitha** [comment]
Hi kiryph,

Yes, I saw that code - I think you linked to it earlier in the thread. But the `pythontex` manual also has config code to invoke `pythontex`, which is a lot simpler. What is the advantage of this code?

**Comment by kiryph** [comment]
Well, my original problem is resolved: pythontex will be automatically invoked on first compilation of a clean state of the latex folder. This means you can clean a latex project with `$ latexmk -c` and then compile it with `$ latexmk` without the need to run pythontex on your own. This fits very well into the the feature set by most editors (e.g. vim+vimtex, ...).
