### ISSUE TITLE
As of Julia 1.0, InteractiveUtils needs to be imported for juliaconsole envs

### ISSUE THREAD

**Issue by tawheeler** [gpoore/pythontex#134]
Several functions available in the real Julia console are no longer available in normal Julia without importing the InteractiveUtils package. 
juliaconsole environments should probably have `using InteractiveUtils` under the hood.

**Comment by tawheeler** [comment]
I tried using `\pythontexcustomc{juliacon}{using InteractiveUtils}`, but that substitutes every other juliaconsole block with ```using InteractiveUtils```, doubling the number of envs that show up :(

**Comment by tawheeler** [comment]
In other news, I expected juliaconcode to execute but not display anything, and it appears to be typesetting. (executing correctly as expected though).

**Comment by gpoore** [comment]
For `using InteractiveUtils`, I'd suggest opening an issue in [Weave.jl](https://github.com/mpastell/Weave.jl), which is being used to do the actual code execution. I may be able to figure out something in the meantime.

Currently, the `juliaconsole` is really a hack on top of a code environment, so no other environments work as expected. I was just reminded of that myself in the last few days...I've been adding a console environment for R, to try to get some ideas about how to redesign things to make it simpler to add console environments. I'll see if I can at least get a proper `juliaconcode` and `\juliaconc` working.

**Comment by tawheeler** [comment]
Awesome, thanks!

**Comment by gpoore** [comment]
`pythontexcustomcode` and `\pythontexcustomc` with `juliacon`, and `juliaconcode` should now work as expected.

**Comment by tawheeler** [comment]
You're awesome! We're incorporating it now. Will close the issue.

**Comment by mykelk** [comment]
Does it make sense to tag a new release at this point? This is pretty nice functionality to have in the version on CTAN.

**Comment by gpoore** [comment]
@mykelk Yes, a new release on CTAN is long overdue. There's a pull request that will [add support for all Jupyter kernels](https://github.com/gpoore/pythontex/pull/149), and I'm hoping to get a new release out once that is merged.
