### ISSUE TITLE
Matplotlib and automatic importation of figures " savefig() missing 1 required positional argument: 'fname'"

### ISSUE THREAD

**Issue by jowe19** [gpoore/pythontex#137]
Hello.

I try this solution (https://github.com/gpoore/pythontex/wiki/matplotlib) in order to include easily a lot of figures in a tex document. Unfortunately I get the following error and I am not able to fix it.

---- Messages for pylab:default:default ----
Traceback (most recent call last):

PythonTeX stderr - error on line 26:
File "/pylab_default_default.py", line 70, in 
name = savefig()
File "/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 689, in savefig
res = fig.savefig(*args, **kwargs)
TypeError: savefig() missing 1 required positional argument: 'fname'
\documentclass[11pt]{article}
\usepackage{pythontex}

\begin{pythontexcustomcode}[begin]{pylab}
sys.path.append('/Users/.../DevoirsTPs/TPInfo/')
from python_preambule import *
from matplotlib.pyplot import *
\end{pythontexcustomcode}

\begin{document}

ABCDE

\begin{pylabcode}
x = linspace(0, pi)
plt.plot(x, sin(x), label='sin(x)')
plt.plot(x, cos(x), label='cos(x)')
name = savefig()
fig = latex_figure(name)
\end{pylabcode}
\pylab{fig}

\end{document}

**Comment by gpoore** [comment]
Using the linked approach (https://github.com/gpoore/pythontex/wiki/matplotlib) requires copying the custom `savefig()` function and other functions defined there into your document. Otherwise, for `pylabcode` environments, the existing `savefig()` from matplotlib will be used, causing the error.
