### ISSUE TITLE
How to specify pyconsole's Verbatim options?

### ISSUE THREAD

**Issue by dimv36** [gpoore/pythontex#141]
Hi,

thanks for PythonTeX project. I have two questions:

* How can I specify another fontsize for Verbatim, used for pyconsole and others Environments?
* Can I specify custom Verbatim for Python code output?

**Comment by gpoore** [comment]
All code is typeset using `fancyvrb` (https://ctan.org/pkg/fancyvrb), so you can use its settings to adjust font properties. Or look into using `\setpythontexfv` for more fine-grained, PythonTeX-specific control.

In terms of customizing verbatim code output, I assume you're referring to something like `\printpythontex[verbatim]`? There isn't a built-in way to customize that. However, you can just create a command that wraps `\printpythontex` and sets `fancyvrb` options.

**Comment by dimv36** [comment]
Thanks!

The TeX package fvextra also can be used for Verbatim customization too.
