### ISSUE TITLE
How to format long output of pyconsole blocks?

### ISSUE THREAD

**Issue by reckoner** [gpoore/pythontex#143]
The `print` output of some of my `pyconsole` blocks is quite wide. It is possible to control the width and make the output wrap? Currently, the output flows past the page margin.

**Comment by gpoore** [comment]
You can probably get what you want using the [`fvextra`](https://github.com/gpoore/fvextra) line breaking options.  For example
```latex
\documentclass{article}
\usepackage{pythontex}

\begin{document}

\begin{pyconsole}[][breaklines, breaksymbolleft={}, breakindentnchars=0]
a = 'asfsda sda fsfsd das fasf asf asf as fsaf asf asf asf asfas sadf asdf asd asd asdf asf sad fa s fasf sdaf asd'
a
\end{pyconsole}

\end{document}
```

**Comment by reckoner** [comment]
Thanks! Is there a way to make this the default?

**Comment by gpoore** [comment]
You can use `\fvset`. Or use `\setpythontexfv` to restrict the effects to pythontex rather than everything using `fancyvrb`/`fvextra`.

**Comment by reckoner** [comment]
\setpythontexfv{breaklines,breaksymbolleft={},breakindentnchars=0}

For posterity. Thanks!
