### ISSUE TITLE
Add PythonTeX dependencies in self contained script

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#151]
As mentioned previously and discussed at SciPy 2017 I opted to primarily package functions to be used in PythonTeX as self-contained scripts which are executed with `exec()`: https://github.com/TheChymera/RepSeP/blob/21270a1d30c5a873abcc887f2fa21cd98fe2838a/pythontex/functions.py#L160

While I can thus [add the script itself](https://github.com/TheChymera/RepSeP/blob/21270a1d30c5a873abcc887f2fa21cd98fe2838a/pythontex/functions.py#L144) to the dep list, I cannot find a way to add the data path from within the script. I can do this elsewhere, I know, but this means spelling it out twice, which inevitably exposes the entire system to path divergence.

I have perused the code and it seems the `add_dependencies()` function is in fact a method of a class defined in the `pythontex_utils` module. Any way I can access this functionality for the active session from within a script executed with `exec()`? I am assuming the straight-forward answer is no, since script separation is the whole reason for executing it this way, but is there any more.... creative ... way to accomplish this?

**Comment by gpoore** [comment]
Try replacing `exec(open(script).read())` with `exec(open(script).read(), globals())`. I think you should then be able to use the normal `add_dependencies()` inside `script`.
