### ISSUE TITLE
I can't compile pythontex with texmaker

### ISSUE THREAD

**Issue by MINKIOH** [gpoore/pythontex#154]
Hi, guys.
I am using OS X Mojave and Python 3.7.3, no Anaconda .
I don't know how to compile pythontex whith texmaker.

I tried several things:
1. pdflatex -synctex=1 -interaction=nonstopmode %.tex|python /usr/local/texlive/2019/texmf-dist/scripts/pythontex/pythontex.py %.tex|pdflatex -synctex=1 -interaction=nonstopmode %.tex

2. pdflatex -shell-escape %.tex|pythontex %.tex|pdflatex -shell-escape %.tex

3. pdflatex -shell-escape -8bit %.tex|python /usr/local/texlive/2019/texmf-dist/scripts/pythontex/pythontex.py %.tex|pdflatex -shell-escape %.tex|

4. pdflatex -shell-escape %.tex|pythontex %.tex|pdflatex -shell-escape %.tex|

Then, I can't get any result, just the log show "process started." though \py{3+1}.

**Comment by Aelurus-1** [comment]
Hello,
under windows i use this one, and it works fine.

pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %.tex|python C:\MiKTeX_2.9\scripts\pythontex\pythontex.py %.tex|pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %.tex

My python install is like MikeTex at C:\, try to correct the path in what i give you and put it as a command user.

If it can help
