### ISSUE TITLE
PythonTex not generating plot pdf

### ISSUE THREAD

**Issue by ccaprani** [gpoore/pythontex#163]
Installed PythonTex 0.17 on Ubuntu 18.04 and using TexStudio 2.12.6. Cannot get any plotting code to work, e.g.

```latex
\documentclass{article}
\usepackage{pythontex}
\usepackage{graphicx}
\begin{document}
\begin{pycode}
from pylab import *
figure(figsize=(4,3))
x = linspace(0, 4, 1001)
plot(x, 3*sin(2*pi*x/4))
xlabel('$x$ (m)')
ylabel('$y$ (m)')
grid(True)
savefig('wave.pdf', bbox_inches='tight')
\end{pycode}
\includegraphics[scale=1]{wave}
\end{document}
```
The file `wave.pdf` is not generated. I have confirmed that the python code executes fine using the command line in the same folder and generates the file. The pdflatex - pythontex - pdflatex sandwich is executed in TekStudio using:

```
txs:///pdflatex | pythontex %.tex | txs:///pdflatex | txs:///biber | txs:///pdflatex | txs:///view-pdf-internal --embedded
```
where `txs:///pdflatex` is
```
pdflatex -synctex=1 -interaction=nonstopmode %.tex
```
Other python code executed fine, for example, the pythontex_gallery.pdf is generated correctly, except for the `myplot.pdf` image.

**Comment by gpoore** [comment]
I'd suggest running `pdflatex` and then `pythontex` from the command line, and checking the output (especially the `pythontex` output) to see if there are any error or warnings. Your document is working fine for me.

**Comment by ccaprani** [comment]
Thanks @gpoore I should have done this first. Indeed, that works properly. I guess it is a TexStudio issue then. If you have any advice on this it would be appreciated, but otherwise please close this issue. And thanks for the great work!

**Comment by gpoore** [comment]
You might look at the log/output inside TeXstudio. One possibility is that TeXstudio is somehow using a different version of Python than what you are using at the command line.

**Comment by muzimuzhi** [comment]
TeXstudio stops since the first execution of `txs:///pdflatex` causes file-not-found error (`wave.pdf`). Using 
```tex
\IfFileExists{wave.pdf}{\includegraphics[scale=1]{wave}}{}
```
instead of raw `\includgraphics` avoids the file-not-found error, and makes TeXstudio compile your example as expected.
