### ISSUE TITLE
Is there a way to use existing virual environment (created by Pycharm)

### ISSUE THREAD

**Issue by bedlamzd** [gpoore/pythontex#165]
This is similar to #138 but I cannot find a solution to my case. As in mentioned issue I can use python.exe in the environment, but cannot import libraries.

Now I simply use `pythontex --interpreter $path/to/interpreter` command, but I guess that is wrong way to do it.

**Comment by bedlamzd** [comment]
actually, I've done same thing as in answer to #138. But it is not working as expected. My base python is 3.8 but environment should be 3.7.

**Comment by bedlamzd** [comment]
Turned out my virtual environment somehow used 3.8 python interpreter, instead of 3.7
I created new environment (also removed python from system path to be sure), installed necessary modules (numpy and others) but when compiling it still gives an error `ModuleNotFoundError: No module named 'numpy'` when importing my code

**Comment by bedlamzd** [comment]
Also, using pyconsole environment I can import packages, but not in pycode environment

**Comment by gpoore** [comment]
When you run `pythontex`, `pythontex` itself will run under the version of Python for which `pythontex` is installed. That version of Python will apply to all `pyconsole` environments, because these are executed using the [`code`](https://docs.python.org/3/library/code.html) module within the main `pythontex` process. However, all other Python code (`pycode`, etc.) is executed via subprocess, which defaults to running `python` but can be changed with `--interpreter`.

So depending on how things are configured, `pyconsole` and `pycode` can use different Python versions. An issue for this exists in #24; fixing requires some significant redesign. If you can set `--interpreter python:<path_to_python_you_want>` to the correct value, you should be able to get everything using the same Python version.

**Comment by bedlamzd** [comment]
Thank you for your help!
I solved my problem (I've been using `--interpreter` wrong). But I've noticed weird behavior.
So my commands now are
`"D:\Repositories\vkr\venv37\Scripts\activate.bat" &&  pythontex --interpreter python:D:\\Repositories\\vkr\\venv37\\Scripts\\python.exe %.tex`
to activate environment and specify proper interpreter.
So, as I undestand, `pyconsole` now shold run under system interpreter and `pycode` under specified environment.
But if I do this
<details>
  <summary>Latex file</summary> 

```latex
\documentclass[a4paper, 12pt]{article}

\usepackage{cmap}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english, russian]{babel}
\usepackage[gobble=auto]{pythontex}

\begin{document}
    \section*{py\LaTeX\ }
    In pyconsole
    \begin{pyconsole}
    	import os
    	import sys
    	os.getcwd()
    	sys.version
    	sys.executable
    	import numpy as np
    	np.cos(np.pi)
    \end{pyconsole}
    In pycode\\
    \begin{pycode}
    	import sys
    	import os
    	print(os.getcwd().replace('\\', '/'), r'\\')
    	print(sys.version, r'\\')
    	print(sys.executable.replace('\\', '/'), r'\\')
    	import numpy as np
    	print(np.cos(np.pi))
    \end{pycode}
\end{document}
```
</details>

they both work and give following results
<details>
<summary>resulted pdf</summary>

![image](https://user-images.githubusercontent.com/44726005/76679788-5161a200-65f4-11ea-9363-e18d29026dfe.png)
</details>

and in the same time, interpreter specified by `pyconsole` actually does not have numpy installed
<details>
<summary>cmd numpy check</summary>

```
C:\Users\bedla>py -3.7
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'C:\\Users\\bedla\\AppData\\Local\\Programs\\Python\\Python37\\python.exe'
>>> import numpy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>>                                           
```
</details>

and all this while my base python interpreter actually 3.8 (3.7 not in the PATH)
<details>
<summary>cmd python version check</summary>

```
C:\Users\bedla>python -V
Python 3.8.2                                            
```
</details>

So, to conclude
Activation of the environment affects `pyconsole` as follows:

1. changes interpreter to a system interpreter with the same version as in environment
2. adds modules of the environment
3. does not specify interpreter of the environment.

Activation of the environment affects `pycode` as follows:

1. changes interpreter to a system interpreter with the same version as in environment
2. does not add modules of the environment
3. does not specify interpreter of the environment. (but it could be specified manually)
