### ISSUE TITLE
Flatten tex file containing python code (e.g. for publishing)

### ISSUE THREAD

**Issue by student-sx** [gpoore/pythontex#175]
Is there any way to "flatten" a tex document which uses pythontex? I.e. output another tex document, that you can compile without pythontex and get the same result. 

For example if you want to submit a paper to a publisher, that doesn't support pythontex, this would be nice.

**Comment by gpoore** [comment]
Take a look at `depythontex` in the documentation. It has some limitations, but if you don't do anything particularly complicated, it should work.

Depending on what you are doing, you could also look at Codebraid (https://github.com/gpoore/codebraid/), which is sort of like PythonTeX for Markdown. It uses Pandoc Markdown as input, but that allows embedded LaTeX, and Pandoc can output a variety of formats.
