### ISSUE TITLE
LaTeX package dependent on PythonTeX; setting the appropriate path

### ISSUE THREAD

**Issue by amosborne** [gpoore/pythontex#178]
Hello - I'm quite new to LaTeX and have a package on CTAN called PuyoTikZ ([link](https://ctan.org/pkg/puyotikz?lang=en)).

I've come to realize that this package cannot work because in `puyotikz.sty` where I call `\pyc{import puyotikz as puyo}`, `puyotikz.py` (installed in the typical `texmf-dist/scripts/puyotikz/` directory is not on the system path and therefore cannot be found for importing.

I've looked through the PythonTeX source code but I can't locate how you are able to setup your system path appropriately. How do you do it, and what do you recommend I do to fix my path as well?

My (perhaps dumb) solution would be to include some Python code in my `puyotikz.sty` file to find the path to `pythontex.py` in `sys.path` and then add the path to `puyotikz.py` relative to that.

Thank you for the help, Alex

**Comment by amosborne** [comment]
Having corresponded with the kind folks over at TeXLive, we landed on using the `kpsewhich` tool to locate the proper path. I simply add the path in my `puyotikz.sty` file. [Here](https://github.com/amosborne/puyotikz/commit/8250617f524c79e0b958d694a0f223bb35c49a5b) is the commit where I make the change. I will close this issue- perhaps it will be useful as a reference to others in the future.

**Comment by gpoore** [comment]
`kpsewhich` should be a good approach. I'm only aware of the implementation details of one other package that uses PythonTeX internally, and I think it does the same thing.
