### ISSUE TITLE
Referencing labels in source code

### ISSUE THREAD

**Issue by grwlf** [gpoore/pythontex#179]
Hi. I'm trying to put a `\label{foo}` to my source code and then reference it using `\ref{foo}`. My document looks like the following:

```tex
\documentclass{article}
\usepackage[rerun=always, pygopt={texcomments=true}]{pythontex}
...
\begin{document}
...
\setpythontexfv{breaklines, breakafter=0123456789-, commandchars=\\\{\}}
\begin{pyblock}[stdout]
from subprocess import check_output
rref:RRef = realize(instantiate(stage_hello))
print(check_output(mklens(rref).out_bin.syspath, shell=True)) # \label{foo}
\end{pyblock}
Result:
\stdoutpythontex
Ref to foo: \ref{foo}
\end{document}
```

The resulting PDF does not contain `\label`, which AFAIK means that `texcomments=true` worked. But it also doesn't contain the reference, which I can't explain.

```
LaTeX Warning: Reference `foo' on page 1 undefined on input line 156
```

Could it be a bug? 

Note that I _don't_ use `depythontex` here.

**Comment by gpoore** [comment]
Your example seems to be working for me. I do have to run LaTeX a few times after PythonTeX for the reference to resolve.

**Comment by grwlf** [comment]
> Your example seems to be working for me. I do have to run LaTeX a few times after PythonTeX for the reference to resolve.

Wow, it looks like I was hit by problem so old, that it looks more like a cultural heritage now. Like quitting from vim. Thank you, now I have made it. The `rm` line removed temporary files so latex obviously had to be called third time :) Final compilation procedure looks like this now:
```shell
set -e -x
F="$1"
rm -rf pythontex-files-* || true
pdflatex --shell-escape -interaction=nonstopmode "$F"
pythontex "$F"
pdflatex --shell-escape -interaction=nonstopmode "$F" || true
pdflatex --shell-escape -interaction=nonstopmode "$F" # Had to add this line
```
