### ISSUE TITLE
Floating environment with `texcomments=true`

### ISSUE THREAD

**Issue by reckoner** [gpoore/pythontex#180]
I understand that it is possible to reference individual lines in a code block using `texcomments=true` but those references have to point to a floating environment that contains the code block, right? I don't understand how to set up the floating environment ( maybe with a caption ) so that the code that is referenced in the text will point to the correct code block.

**Comment by gpoore** [comment]
You can do something like this. The floating environment isn't necessary for referencing, though.
```latex
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[pygopt={texcomments=true, mathescape=true}]{pythontex}

\begin{document}

\begin{listing}
\begin{pyverbatim}
a = 1
b = 2 # \label{lastline}
\end{pyverbatim}
\caption{\label{code1}Caption}
\end{listing}

In listing \ref{code1}, line \ref{lastline} is labeled.

\end{document}
```

**Comment by reckoner** [comment]
Is the floating environment necessary for the caption? Would this work with `pyconcode` also?

**Comment by gpoore** [comment]
If you want a caption, you need either a floating environment, or some sort of environment that doesn't float but otherwise supports captions etc. This works with `pyconsole` and should generally work with the environments that display code.

**Comment by reckoner** [comment]
Is it possible to have line numbering in the displayed  `pyconsole`? I can get the `\caption` to work but it references a line of code that itself is not numbered and requires the reader to count lines in the displayed `pyconsole`.

**Comment by gpoore** [comment]
You can use `\begin{pyconsole}[][numbers=left]`, or you can use `\setpythontexfv{numbers=left}` to apply to all environments.

**Comment by reckoner** [comment]
Thanks for the big help!
