### ISSUE TITLE
cannot use \pycode inside tabular environment

### ISSUE THREAD

**Issue by ghost** [gpoore/pythontex#25]
Hi,

I cannot use \pycode inside the tabular environment:

```
\begin{tabular}{|c|c|c|c|c|}
\begin{pycode}
print("a & b & c & d & e \\\\")
\end{pycode}
\end{tabular}
```

The temp `stdout` file seems to have the correct form:

```
a & b & c & d & e \\
```

But I got this error message:

```
! Missing \endgroup inserted.
<inserted text>
            \endgroup
l.1 a &
    b & c & d & e \\
```

I use texlive2013 and `xelatex` to compile my document. I obtained `pythontex` package from CTAN.
Since I'm an Arch linux user, the default `python` interpreter is Python 3.

**Comment by obtitus** [comment]
Just as an update matrix2latex, which attempts to be a simple method for constructing LaTeX tables in python (and matlab), now lives here: https://github.com/TheChymera/matrix2latex
