### ISSUE TITLE
pdfTeX error (font expansion): auto expansion is only possible with scalable

### ISSUE THREAD

**Issue by bsamadi** [gpoore/pythontex#32]
When I compiled pythontex_quickstart.tex, I got the following error:

pdfTeX error (font expansion): auto expansion is only possible with scalable

I searched for the solution, and then added:
\usepackage{lmodern}
to the file and then everything worked fine. I was wondering if there is a better solution? and should the file be updated?

**Comment by koppor** [comment]
This is a usual issue in the context of MiKTeX. Solution: Install the [cm-super](https://www.ctan.org/pkg/cm-super) package using the MiKTeX package manager. Then, run `initexmf --mkmaps` on the command line. (Long description: http://tex.stackexchange.com/a/324972/9075)

**Comment by kernel1983** [comment]
the command line to fix this is

    mpm --install=cm-super

it may takes a while because around 65M data need to be downloaded
