### ISSUE TITLE
Obtaining the output of an expression when usefamily=jl

### ISSUE THREAD

**Issue by dmbates** [gpoore/pythontex#51]
I am using PythonTeX to create a document with Julia code.  I would like to include the value of the expression as well as the expression itself.  A `jlblock` environment evaluates the expression and prints the expression but not the value.  I don't see any Julia equivalent of the pycon family.

Can anyone tell me how to accomplish this?

**Comment by mlhetland** [comment]
The [doctest mechanism](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/DocChecks.jl#L130) of the official documentation package seems to just walk through the lines and use `eval`, wrapped up in a custom [`eval_repl`](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/DocChecks.jl#L194) function. It may be that a bit of what they do could be avoided if all you need is the output (i.e., not to separate input from output, to check the output, to check exceptions, etc.)?

**Comment by mlhetland** [comment]
Ah, brilliant!
