### ISSUE TITLE
v0.14 package update for Gentoo

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#57]
Hi, I see on the readme that pythontex is now v0.14 - but I can only download the 0.12 zip. How do I get 0.14?

**Comment by obtitus** [comment]
Are you using the "Download ZIP" on the (bottom) right hand side of https://github.com/gpoore/pythontex/ ? That seems to give me 0.14

**Comment by gpoore** [comment]
The "releases" button in the top center-right of the page leads to current downloads. I'm no longer using the `package_downloads` directory, so I should probably delete it.

**Comment by TheChymera** [comment]
ok, many thanks :) I updated the sources location for my version bumped ebuild. Speaking of which, I'm the one maintaining the Gentoo ebuild for PythonTeX - but I have a rather poor understanding of how it works internally. I remember for v0.12 I had to sed a few files. Do I still need to do the same pre-install operations seen [here](https://github.com/TheChymera/neurogentoo/blob/b05dfbda865fe3f9a82f25f4958cf867f8d4fd49/dev-tex/pythontex/pythontex-0.14.ebuild#L31-L70) for 0.14?

**Comment by TheChymera** [comment]
Ok, so currentl my new ebuild fails [here](https://github.com/TheChymera/neurogentoo/blob/66bc7290bfbd258c3c550945aa85ff74afe864e9/dev-tex/pythontex/pythontex-0.14.ebuild#L35). I tried testing this manually, and I get the following back from latex:

```
zenbookhost chymera # latex /var/tmp/portage/dev-tex/pythontex-0.14/work/pythontex-0.14/pythontex/pythontex.ins 
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode

(/var/tmp/portage/dev-tex/pythontex-0.14/work/pythontex-0.14/pythontex/pythonte
x.ins
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 2 languages loaded.
(/usr/share/texmf-dist/tex/latex/base/docstrip.tex
Utility: `docstrip' 2.5d <2005/07/29>
English documentation    <2014/04/19>

**********************************************************
* This program converts documented macro-files into fast *
* loadable files by stripping off (nearly) all comments! *
**********************************************************

********************************************************
* No Configuration file found, using default settings. *
********************************************************

)

Generating file(s) ./pythontex.sty 
! Cannot find file pythontex.dtx.
\readsource ...ot find file \uptospace #1 \qStop }
                                                  \else \processedLines \z@ ...
l.40 ...ontex.sty}{\from{pythontex.dtx}{package}}}
                                                  
? 
*************************************************************
*                                                           *
* To finish the installation you have to move the following *
* file into a directory searched by TeX:                    *
*                                                           *
*     pythontex.sty                                          *
*                                                           *
* To produce the documentation run the file pythontex.dtx    *
* through LaTeX.                                            *
*                                                           *
* Happy TeXing!                                             *
*                                                           *
*************************************************************
 )
No pages of output.
Transcript written on pythontex.log.
```

Any ideas what could be wrong?

**Comment by obtitus** [comment]
The output (clearly?) states that it cannot find pythontex.dtx, some ideas:
1) Ensure the file is there
2) Change the working directory before running latex pythontex.ins
3) See if the latex command has a way of specifying the location of the dtx.

But more importantly: Consider if you need to run the command at all? Installing pythontex is only about moving files into the correct location.

**Comment by TheChymera** [comment]
@obtitus so where shuld I put `pythontex.ins`?

**Comment by gpoore** [comment]
@TheChymera You want `pythontex.dtx` and `pythontex.ins` in the same directory. Running `latex pythontex.ins` generates the `pythontex.sty` from the `pythontex.dtx`.

**Comment by TheChymera** [comment]
@gpoore so it's not just a question of copying files around? I need to run the latex line?

**Comment by gpoore** [comment]
You either use a pre-built style file `pythontex.sty`, or you build it from `pythontex.dtx` and `pythontex.ins`. If you use the pre-built version, then there is no need to run `latex pythontex.ins`. The error you are getting, though, is from running `docstrip`, which is what `latex pythontex.ins` does. As obtitus pointed out, the error is that `pythontex.dtx` is missing during this process.

**Comment by TheChymera** [comment]
what system folder should I put these files pythontex.py, depythontex.py and syncpdb.py into?

**Comment by gpoore** [comment]
@TheChymera I keep them under `texmf-dist/scripts/pythontex` within the TeX distribution, which is where TeX Live puts them in a typical installation. But the ebuild system may have a different setup that would put them elsewhere; I've never used Gentoo.
