### ISSUE TITLE
Bad interaction between listings and pythontex

### ISSUE THREAD

**Issue by fmitha** [gpoore/pythontex#61]
The following MWE

```
\documentclass{article}
\usepackage{listings}
\usepackage{pythontex}
\begin{document}
\end{document}
```

gives an error.

```
ERROR: You can't use `\relax' after \the.

--- TeX said ---
<recently read> \c@float@type

l.4 \begin{document}

--- HELP ---
From the .log file...

I'm forgetting what you said and using zero instead.
```

I've also reported this by email. This might not be a pythontex bug, in which case, please close it.

**Comment by gpoore** [comment]
`pythontex` loads the `newfloat` package to create a `listing` float, and it looks like this is interfering with `listings`. You could try loading `pythontex` before `listings`. That eliminates the error for me, though it's possible another error will appear once there's an actual document with code and a list of listings. You could also consider using the `\pygment` and `pygments` provided by `pythontex` for code typesetting.

If you try changing the order of the packages, let me know how that works.

I will come back to this when I'm working on the next release and see if I can track the conflict further.

**Comment by obtitus** [comment]
I use \usepackage{pythontex} followed by \usepackage{listings} all the time, works great. 
(Still using listings out of habit, even tough pythontex provides a hook into pygment).

**Comment by fmitha** [comment]
Hi Geoffrey,

Thank you for the quick reply.

On Wed, 11 Mar 2015, Geoffrey Poore wrote:

> pythontex loads the newfloat package to create a listing float, and it 
> looks like this is interfering with listings. You could try loading 
> pythontex before listings. That eliminates the error for me, though it's 
> possible another error will appear once there's an actual document with 
> code and a list of listings. You could also consider using the \pygment 
> and pygments provided by pythontex for code typesetting.

> If you try changing the order of the packages, let me know how that works.

Yes, changing the order makes the error go away, even in the original file 
in which I saw the error, though I hardly use listings there. Sorry, I 
should have mentioned that in the original report. However, this was not 
obvious in the original context in which I saw this error. Much stripping 
down of my LaTeX file was required before the problem became clear.

> I will come back to this when I'm working on the next release and see if 
> I can track the conflict further.

Ok, thanks.

     Regards, Faheem

**Comment by eg9** [comment]
The bug is in `newfloat`, lines 70-72

```latex
  \ifdefined\c@float@type % from float package
    \expandafter\edef\csname ftype@#2\endcsname{\the\value{float@type}}%
    \addtocounter{float@type}{\value{float@type}}%
```

Since `listings` does `\@ifundefined{c@float@type}` (a check whether `float` is being loaded), it leaves `\c@float@type` equivalent to `\relax`.

Also `newfloat` should use `\@ifundefined`.

See https://tex.stackexchange.com/a/416739/4427
