### ISSUE TITLE
Refining SAGE support

### ISSUE THREAD

**Issue by gpoore** [gpoore/pythontex#63]
SAGE support was added in response to http://tex.stackexchange.com/questions/232880.

This issue is for refining the initial attempt at SAGE support.

**Comment by anteprandium** [comment]
I get the following error (on OSX stock python):

    Snotra:pysage.texd koji$ python pythontex/pythontex.py new
    This is PythonTeX 0.14
    Traceback (most recent call last):
       File "pythontex/pythontex.py", line 62, in <module>
        pythontex.main()
      File "/Users/koji/Documents/Misc/pysage.texd/pythontex/pythontex2.py", line 2649, in main
        do_multiprocessing(data, temp_data, old_data, engine_dict)
      File "/Users/koji/Documents/Misc/pysage.texd/pythontex/pythontex2.py", line 1367, in     do_multiprocessing
        result = task.get()
      File     "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line     554, in get
        raise self._value
    UnboundLocalError: local variable 'script' referenced before assignment
    Snotra:pysage.texd koji$

**Comment by gpoore** [comment]
It should work now. There was a bug from refactoring that I didn't catch due to caching.

**Comment by anteprandium** [comment]
Mmm. I am still having trouble, sorry to keep pestering. I get the following now:

    This is PythonTeX 0.14

    ----  Messages for sage:default:default  ----
    * PythonTeX error
        An error occurred but no error messages were identified.
        This may indicate a bad command or missing program.
        The following command was executed:
            "sage pythontex-files-new/sage_default_default.sage.py"
      CRITICAL:root:unknown notebook: None

    --------------------------------------------------
    PythonTeX:  new - 1 error(s), 0 warning(s)

I do have a `sage` shell script in my path (though not in the system path, the script is located in ~/Scripts and i add ~/Scripts to the path).

**Comment by gpoore** [comment]
It's finding `sage`, because the preparse step worked; otherwise, it wouldn't have gotten this far.

This looks like the SAGE bug that prevents file/path names containing the string `-n` from working properly: http://ask.sagemath.org/question/25624/sagetex-hyphen-in-filename-forbidden/. I'm using the latest version of SAGE, so I wasn't getting this.

A simple workaround, to avoid upgrading, would be to use a file name that doesn't begin with the character `n`, or to use a custom output directory. This can be done in the .tex file, after loading `pythontex`, with `\setpythontexoutputdir`. Maybe try `\setpythontexoutputdir{pythontex_files_new}`.

**Comment by anteprandium** [comment]
Now it works beautifully!! Thanks again, this is great news for me.

**Comment by anteprandium** [comment]
I did some more testing, and I actually had time to look in more detail at your code. I noted this when creating the sage engine: 

    SubCodeEngine('python', 'sage', language='sage', extension='.sage',
                  template=python_template.replace('{future}', ''),
                  extend = 'pytex.formatter = latex',
                  commands=['{sage} --preparse {file}.sage',
                            '{sage} {file}.sage.py'],
                  created = '{file}.sage.py')

But SAGE will preparse by default `.sage` files, so the following is enough:

    SubCodeEngine('python', 'sage', language='sage', extension='.sage',
                  template=python_template.replace('{future}', ''),
                  extend = 'pytex.formatter = latex',
                  commands=['{sage} {file}.sage'])

So,  for this use case, there's no need for the new capability of more than one command, but I think at some point in the future it will pay off :)

**Comment by gpoore** [comment]
That's good to know. I'll use the simplified version for the next release.
