### ISSUE TITLE
pytex.context is not available in pythontexcustomcode section

### ISSUE THREAD

**Issue by Cadair** [gpoore/pythontex#65]
Hi,

I am trying to use the `pytex.context` dict to do some matplotlib configuration in the `pythontexcustomcode` environment, however it appears the context dict is not available?

**Comment by gpoore** [comment]
That's a bug. Here's a patch you can add in the preamble, right after loading `pythontex` and before using `pythontexcustomcode`. I'm going to try to get a bug-fix release out in the next couple weeks, and will put this in it.

```latex
\makeatletter
\renewenvironment{pythontexcustomcode}[2][begin]{%
    \VerbatimEnvironment
    \Depythontex{env:pythontexcustomcode:om:n}%
    \ifstrequal{#1}{begin}{}{%
        \ifstrequal{#1}{end}{}{\PackageError{\pytx@packagename}%
            {Invalid optional argument for pythontexcustomcode}{}
        }%
    }%
    \xdef\pytx@type{CC:#2:#1}%
    \edef\pytx@cmd{code}%
    % PATCH \def\pytx@context{}%
    \pytx@SetContext
    % END PATCH
    \def\pytx@group{none}%
    \pytx@BeginCodeEnv[none]}%
{\end{VerbatimOut}%
    \setcounter{FancyVerbLine}{\value{pytx@FancyVerbLineTemp}}%
    \stepcounter{\pytx@counter}%
}%
\makeatother
```

**Comment by Cadair** [comment]
thanks for the patch.

FYI, I am working on a library of figure helpers, https://github.com/Cadair/texfigure it's quite early at the moment, but hopefully it will become quite useful.

**Comment by gpoore** [comment]
The figure helpers look like they could be very useful. Let me know if you come across any cases where you need functionality that doesn't currently exist.

**Comment by andsor** [comment]
Hi thanks for the patch (and the whole PythonTeX effort!). Just wanted to chip in that I also ran into this issue and support putting this in.

**Comment by gpoore** [comment]
@andsor Unfortunately, I haven't made many improvements in the code execution side of PythonTeX for a long time...most work has gone into the code typesetting side. I am finally back to working on the code execution side, though, so I'm hoping to fix this and a number of other things in the next few months.
