### ISSUE TITLE
Pythontex and reportlab

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#67]
Hello again!

I am currently using BioPython, which generates figures not via matplotlib, but via reportlab.

Reportlab has no interactive windows, and just writes the figures as PDF, or SVG, or any number of other formats. E.g.

```
GenomeDiagram.Diagram.write("/my_loc.pdf", "PDF")
```

Any idea how I this could be made to work with PythonTeX?

**Comment by gpoore** [comment]
It really depends on what all you want to do. But something like this would be a simple way to generate and automatically include figures (untested).

In `pythontexcustomcode`.
```python
pytex.bio_fignum = 0

def bio_fig(fname=None, caption=None, label=None):
    if fname is None:
        fname = 'biopython_fig_{0}.pdf'.format(pytex.bio_fignum)
    gdd.write(fname, "PDF")
    template = '''
\\begin{{figure}}
\\centering
\\includegraphics{{{fname}}}
\\caption{{ {label} {caption} }}
\\end{{figure}}
'''
    if caption is None:
        caption = ''
    if label is None:
        label = ''
    else:
        if not label.startswith('fig:'):
            label = 'fig:' + label
        label = '\\label{{{0}}}'.format(label)
    template = template.format(fname=fname.rsplit('.', 1)[0], label=label, caption=caption)
    print(template)
    pytex.add_created(fname)
    pytex.bio_fignum += 1
```

And then later as appropriate.
```python
bio_fig(<args>)
```

**Comment by TheChymera** [comment]
@gpoore Hey, I tried the code you suggested, and I am getting:

```
  Traceback (most recent call last):
* PythonTeX stderr - unknown on line 14 in "pycode.tex":
    File "<outputdir>/py_pe_cs3_default.py", line 183, in <module>
      fig_pe_cs3 = bio_fig()
* PythonTeX stderr - error on line -30 in "pycode.tex":
    File "<outputdir>/py_pe_cs3_default.py", line 139, in bio_fig
      gdd.write(fname, "PDF")
  NameError: global name 'gdd' is not defined
```

What should I do? I tried calling `bio_fig()` both as `bio_fig(save_fig(fig_width=4.4, fig_height=2))` or just `bio_fig()` but I am getting the same error. Where should I define what `gdd` is? it is defined in the external function I am caling... should I make it return that?

**Comment by TheChymera** [comment]
I tried to make my function return the `gdd` object, and I modified `bio_fig()` to take the `gdd` object as an argument:

```
def bio_fig(gdd, fname=None, caption=None, label=None):
        if fname is None:
            fname = 'biopython_fig_{0}.pdf'.format(pytex.bio_fignum)
        gdd.write(fname, "PDF")
        template = '''
    \\begin{{figure}}
    \\centering
    \\includegraphics{{{fname}}}
    \\caption{{ {label} {caption} }}
    \\end{{figure}}
    '''
        if caption is None:
            caption = ''
        if label is None:
            label = ''
        else:
            if not label.startswith('fig:'):
                label = 'fig:' + label
            label = '\\label{{{0}}}'.format(label)
        template = template.format(fname=fname.rsplit('.', 1)[0], label=label, caption=caption)
        print(template)
        pytex.add_created(fname)
        pytex.bio_fignum += 1
```

Now the code returns no errors, but it just displays “None” in lieu of my figure :-/ any ideas?

**Comment by TheChymera** [comment]
I am noticing that bulding my LaTeX document does produce a file called `biopython_fig_0.pdf` (and which includes all the right contents), I tried including that manually, and that works too. Trying to get any output at all from `bio_fig()`, however, failed:

(the following also just returns “None”)

```
def bio_fig(gdd, fname=None, caption=None, label=None):
        if fname is None:
            fname = 'biopython_fig_{0}.pdf'.format(pytex.bio_fignum)
        gdd.write(fname, "PDF")
        template = '''
    aaaa
    {{fname}}
    \\begin{{figure}}
    \\centering
    \\includegraphics{{{fname}}}
    \\caption{{ {label} {caption} }}
    \\end{{figure}}
    '''
        if caption is None:
            caption = ''
        if label is None:
            label = ''
        else:
            if not label.startswith('fig:'):
                label = 'fig:' + label
            label = '\\label{{{0}}}'.format(label)
        template = template.format(fname=fname.rsplit('.', 1)[0], label=label, caption=caption)
        print(template)
        print("qq")
        pytex.add_created(fname)
        pytex.bio_fignum += 1
```

**Comment by TheChymera** [comment]
Ok, I solved it, they key was to do not `print(template)`, but `return template`

**Comment by TheChymera** [comment]
@gpoore  the fignum counter doesn't work no matter what I do to it. Can you help me out with it?

Also, what would be the most elegant way to have `bio_fig()` put all the figures in the `pythontex-files-<projectname>` folder, like other pythontex functions?

**Comment by gpoore** [comment]
For the fignum, try adding a `global`. I'll have to think about the directory name. I should probably just add it as a part of `pytex`.

**Comment by TheChymera** [comment]
> try adding a `global`

how do I do that? I tried adding it thus:

```
pytex.bio_fignum = 0
def bio_fig(gdd, fname=None, caption=None, label=None):
        if fname is None:
            fname = 'pythontex-files-pres/biopython_fig_{0}.pdf'.format(pytex.bio_fignum)
        gdd.write(fname, "PDF")
        template = '''
    \\begin{{figure}}
    \\centering
    \\includegraphics{{{fname}}}
    \\caption{{ {label} {caption} }}
    \\end{{figure}}
    '''
        if caption is None:
            caption = ''
        if label is None:
            label = ''
        else:
            if not label.startswith('fig:'):
                label = 'fig:' + label
            label = '\\label{{{0}}}'.format(label)
        template = template.format(fname=fname.rsplit('.', 1)[0], label=label, caption=caption)
        print(template)
        pytex.add_created(fname)
        global pytex.bio_fignum
        pytex.bio_fignum += 1
        return template
```

and that fails with ` SyntaxError: invalid syntax` (it seems to particularly dislike the period). If I remove the period it works, but I get this warning:

```
* PythonTeX stderr - warning on line 107 in "functions.tex":
  <outputdir>/py_tp1_default.py:158: SyntaxWarning: name 'pytexbio_fignum' is used prior to global declaration
    global pytexbio_fignum
```

**Comment by obtitus** [comment]
You want the pytex.id in the filename to get it unique (see below).
You should not need the global, but the correct syntax would be something like this:

global pytex # try without this line
def bio_fig(gdd, fname=None, caption=None, label=None):
        global pytex # and this one, should work
        if fname is None:
            fname = 'pythontex-files-pres/biopython_fig_{0}-{1}.pdf'.format(pytex.id, pytex.bio_fignum)
        gdd.write(fname, "PDF")
        template = '''
    \\begin{{figure}}
    \\centering
    \\includegraphics{{{fname}}}
    \\caption{{ {label} {caption} }}
    \\end{{figure}}
    '''
        if caption is None:
            caption = ''
        if label is None:
            label = ''
        else:
            if not label.startswith('fig:'):
                label = 'fig:' + label
            label = '\\label{{{0}}}'.format(label)
        template = template.format(fname=fname.rsplit('.', 1)[0], label=label, caption=caption)
        print(template)
        pytex.add_created(fname)
        pytex.bio_fignum += 1
        return template

**Comment by TheChymera** [comment]
@obtitus that's prtty much the code I first started with (except without an initial `pytex.bio_fignum` declaration). In your code it looks like the variable is used without first being defined? :-/

**Comment by obtitus** [comment]
yeah, sorry, you do of-course also need a
pytex.bio_fignum = 0
before def bio_fig…

The missing part is the pytex.id, which is a unique session key defined by pythontex. You definitely want this in the auto-figure filenames.

**Comment by gpoore** [comment]
@TheChymera I haven't had access to a computer with internet access for several days, and am just getting caught up on this. It looks like everything is resolved, but let me know if there are any additional issues.

**Comment by TheChymera** [comment]
this works now, `pytex.id` was really the missing bit here. Many thanks @obtitus !
