### ISSUE TITLE
Running pythonTeX with Lyx 2.4.1 in Windows 10

### ISSUE THREAD

**Issue by nlooije** [gpoore/pythontex#72]
Hi,
I am [trying](http://tex.stackexchange.com/questions/267779/running-pythontex-with-lyx-under-windows) to run your awesome software in LyX but i am getting weird error messages:

    10:16:43.395: pythontex.bat "test.tex"
    10:16:43.396: 
    10:16:43.398: C:\Users\niels\AppData\Local\Temp\lyx_tmpdir.TNpqvRd10760\lyx_tmpbuf0>python "c:/users/niels/documents/localtexmf/scripts/pythontex/pythontex.py" test.tex 
    10:16:43.436: Traceback (most recent call last):
    10:16:43.437:   File "c:/users/niels/documents/localtexmf/scripts/pythontex/pythontex.py", line 50, in <module>
    10:16:43.438:     import pythontex2 as pythontex
    10:16:43.439:   File "c:\users\niels\documents\localtexmf\scripts\pythontex\pythontex2.py", line 60, in <module>
    10:16:43.440:     import multiprocessing
    10:16:43.441: ImportError: No module named multiprocessing
    ..\..\..\src\support\Systemcall.cpp (292): Systemcall: 'pythontex.bat "test.tex"' finished with exit code 1
    Error: Cannot convert file
    ----------------------------------------
    An error occurred while running:
    pythontex.bat "test.tex"
    10:16:45.227: Error while exporting format: PDF (pytex)

For some reason it doesn't seem to import the `multiprocessing` module. This module is installed and works fine when the scripts are run from the command prompt. Any idea what is going on?

**Comment by obtitus** [comment]
This seems unrelated to pythontex. I would guess that LyX does not have the correct sys.paths, and so fails to find standard python modules. You could try to sneak in a:
'
import sys
print sys.path
‘
into users/niels/documents/localtexmf/scripts/pythontex/pythontex.py somewhere before line 50.

Or see in LyX preferences if you can find anything path related. Good luck,

**Comment by nlooije** [comment]
You are right. LyX was using its own version of Python. Using my installed version of Python remedied the problem. Thanks for your time.

**Comment by gpoore** [comment]
I've added a note on LyX to the docs and quickstart for the next release.

**Comment by Aelurus-1** [comment]
Hello,
I am trying  to run python under Lyx also, python , Lyx 2.3.3, under windows.
When I compile all python script

`\begin{pycode}
	print('llamas!')
\end{pycode}
\py{2+2}` 

just return ?? in the PDF compilation. These is working fine under textlive. 

In lyx Preferences i found this prefixe PATH : 
$LyXDir\bin;$LyXDir\Python;$LyXDir\Python\Lib;$LyXDir\Perl\bin;$LyXDir\imagemagick;C:\MiKTeX_2.9\miktex\bin\x64;C:\Program Files (x86)\LyX 2.3\ghostscript\bin;C:\Program Files\Inkscape;C:\Program Files (x86)\Gnumeric\1.12.17\bin\

If I replace $LyXDir\Python by C:\Python37 witch is myPython install path, the output dont change. I would like to understand how to make it work.

With texmaker i put this commande for compiling : 
pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %.tex|python C:\MiKTeX_2.9\scripts\pythontex\pythontex.py %.tex|pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %.tex
 In Lyx i try to add format and way to compile but it just make many miss.

Can i have some help, way to do it ?

thanks
