### ISSUE TITLE
Getting memory address instead of figure 

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#75]
I am getting `¡function plot at 0x7f7943df5d70¿` instead of my figure when trying to compile the following [tex document]
(https://bitbucket.org/TheChymera/ld_expert-doc/src/fc8796de9acf?at=master).

Can you please help me out? I am using pythontex-0.14-r1 and the live version, and the problem manifests equally with either. It also seems to be independent of whether my function ends in `plt.show` or `plt.savefig()`.

**Comment by gpoore** [comment]
The line `\py[plot]{plot}` won't **call** the plot function, but will rather return the memory address of the `plot()` function. You need to add parentheses and arguments to actually call the function.
