### ISSUE TITLE
PythonTeX system install access violation

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#78]
Hey, it seems a path (`/var/cache/fonts/tfm/unknown/unknown`) is hard coded into PythonTeX. This causes the gentoo package manager to break off the install with an access violation error. Neither me nor a number of the gentoo package maintainers were able to fix this on the Gentoo side of things, and I was told this suggests the above path might actually be hard-coded into PythonTeX. @gpoore  could you double-check to see?

Here is our discussion, for more details: https://github.com/gentoo-science/sci/issues/471

**Comment by gpoore** [comment]
That isn't hard coded.

It looks like LaTeX tries to run to create the documentation (from `pythontex.dtx`), needs to generate a font, and tries to access a restricted location.  A quick web search for `"/var/cache/fonts/tfm"` turns up a number of similar issues. So this looks like a Linux LaTeX config issue.

**Comment by TheChymera** [comment]
ok, you were right. I could fix this via texlive .
