### ISSUE TITLE
Use \textwidth in PythonTex save_fig

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#80]
I am currently saving my figures via:

```
def save_fig(name='', legend=False, fig=None, ext='.pgf', fig_width=1, fig_height=1):
    '''
    Save the current figure (or `fig`) to file using `plt.save_fig()`.
    If called with no arguments, automatically generate a unique filename.
    Return the filename.
    '''
    # Get name (without extension) and extension
    if not name:
        global fig_count
        # Need underscores or other delimiters between `input_*` variables
        # to ensure uniqueness
        name = 'auto_fig_{}-{}'.format(pytex.id, fig_count)
        fig_count += 1
    else:
        if len(name) > 4 and name[:-4] in ['.pgf', '.svg', '.png', '.jpg']:
            name, ext = name.rsplit('.', 1)

    # Get current figure if figure isn't specified
    if not fig:
        fig = gcf()
    fig.set_size_inches(fig_width,fig_height)
    fig.savefig(name + ext)
    fig.clf()
    return name
```

Is there any way to make python take `\textwidth` from the latex nvironment so that I can specify the dimensions not in inches or centimeters - but in percentages of that?

**Comment by gpoore** [comment]
There are two ways you could do this.
* Use matplotlib's PGF backend. This allows saving plots as PGF code, which will be compiled along with the document. Plots will automatically adjust to the document at compile time, but compiles will take longer (may or may not be noticeable).
* Use `\setpythontexcontext` to pass the value of `\textwidth` to the Python side. For example, `\setpythontexcontext{textwidth=\the\textwidth}` will make the value of `\textwidth` available in `pytex.context.textwidth` on the Python side. The value of `\textwidth` will be in units of TeX points (1/72.27 inch). You can either use macros on the TeX side to convert this to inches or centimeters before passing to Python, or use the conversion functions `pytex.pt_to_in()` and `pytex.pt_to_cm()` on the Python side. More details on this are in Section 4.5 in the docs.
