### ISSUE TITLE
depython tex and removing colors in code

### ISSUE THREAD

**Issue by reckoner** [gpoore/pythontex#84]
My publisher frowns on color in the document. How can I use depythontex to remove the pygment coloring of the Python code blocks?

Thanks!

**Comment by gpoore** [comment]
The default depythontex should convert all code into `verbatim`, which won't use syntax highlighting. You can control this using the `--listing` command-line option.

If you are just submitting a PDF, not the LaTeX source, you could just set the package option `pygments=false`.
