### ISSUE TITLE
Add support for automatic line breaks with pygments

### ISSUE THREAD

**Issue by breedlun** [gpoore/pythontex#92]
It would be very nice if pythontex could handle automatic line breaks when typesetting syntax highlighted code from pygments.  As it is now, my code frequently runs past the edge of the page, so I have to go through and manually put in line breaks.   I may start using minted instead, but it would be nice to stick with pythontex.

I realize that this is on @gpoore's list of potential enhancements already.  I just wanted to put in a vote and get it on the github issues list.

**Comment by gpoore** [comment]
If you upgrade to version 0.15, released a few weeks ago, line breaking works, as well as almost all related and similar features that `minted` had gotten first. I think the only thing still missing is line breaking for inline commands (`\pyv`, `\pygment`, etc.).

Note that if you're using MiKTeX, there is [a bug that causes errors with PythonTeX and `minted`](https://github.com/gpoore/minted/issues/129), and you will have to install the latest version of [`fvextra`](https://github.com/gpoore/fvextra) manually until a fix is released.

**Comment by breedlun** [comment]
Fantastic!  This package is proving very useful to me.

You may want to update your "Modifications to Consider" section because it still says you are considering an automatic line breaking algorithm.  I originally saw that and thought automatic line breaking wasn't implemented yet.

Also you may want to include an example of how to enable automatic line breaking, or maybe just point to your fvextra package for instructions on how to turn on automatic line breaking.  It took me a little bit to figure that out.

**Comment by gpoore** [comment]
Yes, the documentation needs an update.
