### ISSUE TITLE
Overunning lines with ltablex

### ISSUE THREAD

**Issue by RossWilliamson** [gpoore/pythontex#99]
I'm trying to use pythontex with ltablex to output a table that gets output from a python script. I've done a simple example below:

    \documentclass{article}
    %\usepackage{tabularx}
    \usepackage{ltablex}
    \usepackage[keeptemps, runall=true]{pythontex}
    
    \begin{document}
    
    \begin{tabularx}{\linewidth}{lX}
    	HELLO & This is a very very long line which will keep on going and going at least until we go beyond the length of the linewidth \\
    \end{tabularx}
    
    \begin{tabularx}{\linewidth}{lX}
    				\pyc{print("HELLO & This is a very very long line which will keep on going and going at least until we go beyond the length of the linewidth")} \\
    \end{tabularx}
    \end{document}

The output is below in the Figure.  The other interesting thing is if I use tabularx over ltablex it does wrap but not in the same place.  Any thoughts on how I can use pythentex with the ltablex package?
[![Using ltablex][1]][1]
[![Using Tabularx][2]][2]

  [1]: https://i.stack.imgur.com/40U0m.png
  [2]: https://i.stack.imgur.com/qtqRk.png

Full disclosure: I've also asked this quesition on texechange [here](http://tex.stackexchange.com/posts/364164/edit)

**Comment by gpoore** [comment]
Working with pythontex and any sort of tabular environment/package tends to be tricky. There are more details in a [previous issue](https://github.com/gpoore/pythontex/issues/25#issuecomment-26922469), but the end result is that often you need to assemble the entire tabular-style environment on the Python side (including the `\begin`/`\end` environment), and then print it to the LaTeX side. If neither `\py` nor `\pyc` are doing what you want, that is likely the only option.

It's possible that `tabularx` or `ltablex` are different enough from standard tabular that there would be another option, but that would probably require digging into the internals of the package (for that approach, TeX.StackExchange is your best source of information).
